### ISSUE TITLE
Invalid value for `type` (OTP),  must be one of ['STRING', 'EMAIL', 'CONCEALED', 'URL', 'TOTP', 'DATE', 'MONTH_YEAR', 'MENU']

### ISSUE THREAD

**Issue by dslip** [1Password/connect-sdk-python#12]
### Your environment

SDK Version: 1.0.1

Connect Server Version: 1.0.0

OS: Windows10

Python Version: 3.9.4

## What happened?

attempting to retrieve data 
client.get_item("vaultID","itemID")

## What did you expect to happen?

Should have returned item details1

## Steps to reproduce
1. 
create a login on the 1password website, set a field to be used as a one time password with code then attempt to retrieve the data

## Notes & Logs

Traceback (most recent call last):
  File "c:\python_testing\1password-test.py", line 14, in <module>
    print(client.get_item("vaultID--retracted", "itemID--retracted"))
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 76, in get_item
    return self.deserialize(response.content, "Item")
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 294, in deserialize
    return self.__deserialize(data, response_type)
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 377, in __deserialize
    return self.__deserialize_model(data, klass)
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 461, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 354, in __deserialize
    return [self.__deserialize(sub_data, sub_kls) for sub_data in data]  # noqa: E501
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 354, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls) for sub_data in data]  # noqa: E501
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 377, in __deserialize
    return self.__deserialize_model(data, klass)
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\client.py", line 463, in __deserialize_model
    instance = klass(**kwargs)
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\models\field.py", line 70, in __init__
    self.type = type
  File "C:\Python39\lib\site-packages\onepasswordconnectsdk\models\field.py", line 144, in type
    raise ValueError(
ValueError: Invalid value for `type` (OTP), must be one of ['STRING', 'EMAIL', 'CONCEALED', 'URL', 'TOTP', 'DATE', 'MONTH_YEAR', 'MENU']

**Comment by jillianwilson** [comment]
Thanks for the issue creation. The fix is [here](https://github.com/1Password/connect-sdk-python/pull/21) and will be pushed in the next release. However, resolving this issue also revealed an issue in the Connect server, thus you will need to upgrade to version 1.2 or higher of Connect in order to successfully use an OTP field.
